name: gmaps_nav_hud_frame
description: "Shows Google Maps turn-by-turn navigation notifications on the Frame (Android only, due to the requirement to read app notifications)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_notification_listener: ^1.3.4
  frame_msg: ^2.0.0
  image: ^4.2.0
  logging: ^1.2.0
  simple_frame_app: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/sprite.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - assets/frame_app.lua
